# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: kefir
service: fault-tolerant-system

custom:
  answersTableName: answers
  bucketName: fault-tolerant-system-website
  customDomain:
    domainName: { self:custom.apiDomain }
    basePath: api
    certificateArn:
    hostedZoneId:
    createRoute53Record: true
    endpointType: REGIONAL
    securityPolicy: tls_1_3
    apiType: http
    autoDomain: true

constructs:
  static-website:
    type: static-website
    bucketName: ${self:custom.bucketName}
    path: frontend/dist/frontend/browser
    domain:
    certificate:

provider:
  name: aws
  runtime: nodejs22.x
  region: eu-west-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [AnswersTable, Arn]
            - Fn::GetAtt: [WebSocketConnectionTable, Arn]
  environment:
    ANSWERS_TABLE: ${self:custom.answersTableName}
    WEBSOCKET_CONNECTION_TABLE: WebSocketConnections
    WEBSOCKET_API_ENDPOINT: https://1zfci4e0aa.execute-api.eu-west-1.amazonaws.com/dev

  logs:
    httpApi: true

  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:4200
      allowedMethods:
        - GET
        - POST
      allowedHeaders:
        - Content-Type
        - Authorization

  websocketsApiName: dynamodb-stream
  websocketsApiRouteSelectionExpression: $request.body.action # custom routes are selected by the value of the action property in the body
  websocketsDescription: DynamoDB Stream WebSocket API

package:
  individually: true
  include:
    - backend/**
  exclude:
    - '**'
    - '!backend/**'
functions:
  startProcessWithBackoff:
    handler: backend/answers/service.postAnswer

  getAnswers:
    handler: backend/answers/service.getAnswers
    events:
      - httpApi:
          path: /answers
          method: get
  getAnswer:
    handler: backend/answers/service.getById
    events:
      - httpApi:
          path: /answers/{id}
          method: get
  worker:
    handler: backend/worker.processAnswer

    connectionHandler:
      handler: backend/socket.connectionHandler
      events:
        - websocket:
            route: $connect
    disconnectionHandler:
      handler: backend/socket.disconnectionHandler
      events:
        - websocket:
            route: $disconnect
    defaultHandler:
      handler: backend/socket.defaultHandler
      events:
        - websocket:
            route: $default
    dynamodbStreamHandler:
      handler: backend/dynamodb-stream.handler
      events:
        - stream:
            type: dynamodb
            arn:
              Fn::GetAtt: [AnswersTable, StreamArn]
            batchSize: 1
            startingPosition: LATEST

resources:
  Resources:
    AnswersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.answersTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_IMAGE

    WebSocketConnectionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.WEBSOCKET_CONNECTION_TABLE}
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
stepFunctions:
  stateMachines:
    processWithBackoff:
      events:
        - http:
            path: answers
            method: POST
            cors:
              origins:
                - http://localhost:4200
              headers:
                - Content-Type
                - Authorization
              allowCredentials: false
        - stream:
            type: dynamodb
            arn:
              Fn::GetAtt: [AnswersTable, StreamArn]
            startingPosition: TRIM_HORIZON
            batchSize: 1
      definition:
        StartAt: ProcessTask
        States:
          ProcessTask:
            Type: Task
            Resource:
              Fn::GetAtt: [startProcessWithBackoff, Arn]
            Retry:
              - ErrorEquals:
                  - States.ALL
                IntervalSeconds: 2
                BackoffRate: 2.0
                MaxAttempts: 5
            Next: WorkerTask
          WorkerTask:
            Type: Task
            Resource:
              Fn::GetAtt: [worker, Arn]
            Retry:
              - ErrorEquals:
                  - States.ALL
                IntervalSeconds: 2
                BackoffRate: 10.0
                MaxAttempts: 5
            End: true

plugins:
  - serverless-lift
  - serverless-domain-manager
  - serverless-scriptable-plugin
  - serverless-step-functions
